### ISSUE TITLE
Getting KeyError after running any command 

### ISSUE THREAD

**Issue by vivekaltruist** [johann-petrak/licenseheaders#47]
I tried running the commands using python 3.8 but getting
`$ licenseheaders --help
Traceback (most recent call last):
  File "/usr/local/bin/licenseheaders", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/licenseheaders.py", line 612, in main
    arguments = parse_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/licenseheaders.py", line 304, in parse_command_line
    known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in typeSettings.items()]
  File "/usr/local/lib/python3.8/site-packages/licenseheaders.py", line 304, in <listcomp>
    known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in typeSettings.items()]
KeyError: 'extensions'`

**Comment by hakonanes** [comment]
Same here, both on Python 3.7.9 and 3.8.4.

**Comment by hakonanes** [comment]
So the fixes made in PR https://github.com/johann-petrak/licenseheaders/pull/48 apparently solved the problem.

**Comment by phcerdan** [comment]
Hitting this error in the pypi version `licenseheaders-0.8.6-py3-none-any.whl `

**Comment by 2BitSalute** [comment]
> So the fixes made in PR #48 apparently solved the problem.

Specifically, adding under **cmake** (line ~145):
     `"extensions": [],`
