### ISSUE TITLE
KeyError: 'opt_dummy_attribute'

### ISSUE THREAD

**Issue by F-I-D-O** [johann-petrak/licenseheaders#50]
Hi,
I tried the package using the full path to the lgpl-v3.tmpl template file (as using the name does not work as mentioned in another issue). I ended up with the following error:

  ```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
File "C:\Program Files\Python39\lib\site-packages\licenseheaders.py", line 899, in <module>
    sys.exit(main())
  File "C:\Program Files\Python39\lib\site-packages\licenseheaders.py", line 799, in main
    template_lines = read_template(os.path.abspath(opt_tmpl), settings, arguments)
  File "C:\Program Files\Python39\lib\site-packages\licenseheaders.py", line 512, in read_template
    lines = [Template(line).substitute(vardict) for line in lines]
  File "C:\Program Files\Python39\lib\site-packages\licenseheaders.py", line 512, in <listcomp>
    lines = [Template(line).substitute(vardict) for line in lines]
  File "C:\Program Files\Python39\lib\string.py", line 121, in substitute
    return self.pattern.sub(convert, self.template)
  File "C:\Program Files\Python39\lib\string.py", line 114, in convert
    return str(mapping[named])
KeyError: 'opt_dummy_attribute'
```

**Comment by johann-petrak** [comment]
This is weird, there is no variable or any string in the code that is named "opt_dummy_attribute"

Did you modify the template?

**Comment by F-I-D-O** [comment]
Oh, sorry, my bad, I tried to save time and downloaded the template from GitHub, but the browser saved the content of the HTML page to the file instead of the raw file, despite the `tmpl` extension. Now it works. Btw I've found the templates at `Program Files/Python39/templates`  folder.

**Comment by johann-petrak** [comment]
Thanks, I will close this then.
