### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9

### ISSUE THREAD

**Issue by arthurlogilab** [johann-petrak/licenseheaders#9]
```
Traceback (most recent call last):
  File "/home/arthur/local/licenseheaders/licenseheaders.py", line 470, in <module>
    sys.exit(main())
  File "/home/arthur/local/licenseheaders/licenseheaders.py", line 424, in main
    dict = read_file(file)
  File "/home/arthur/local/licenseheaders/licenseheaders.py", line 288, in read_file
    lines = f.readlines()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 262: invalid continuation byte
```

**Comment by johann-petrak** [comment]
This is a problem with the file which is most likely not a Unicode (utf8) file. Currentl this program explicitly expects UTF8 encoded files. It would probably be possible to add an option to choose a different encoding.

**Comment by johann-petrak** [comment]
Added an option to choose another encoding for (all) source files. Please test if this fixes your issue if you specify the proper encoding of that file.
